#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)

display_mode=$(cat /sys/class/display/mode)
# default values
display_mode_user="1080p60hz"
frac_rate_policy_user="0"

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    frac_rate_policy=*)
      frac_rate_policy_user=${arg#*=}
      ;;
    vout=*)
      vout=${arg#*=}
      display_mode_user=${vout%%,*}
      # implementation not yet finished by Amlogic
      #frac_rate_policy_user="0"
      #if [ -z ${vout##*frac*} ]; then
      #  frac_rate_policy_user="1"
      #fi
      ;;
  esac
done

# Enable HDMI output if cable is connected and not already enabled by u-boot
if [ "$(cat /sys/class/amhdmitx/amhdmitx0/hpd_state)" != "0" ]; then
  frac_rate_policy=$(cat /sys/devices/virtual/amhdmitx/amhdmitx0/frac_rate_policy)
  if [ "${frac_rate_policy}" != "${frac_rate_policy_user}" ]; then
    display_mode="null"
    echo "${display_mode}" > /sys/class/display/mode
    echo "${frac_rate_policy_user}" > /sys/devices/virtual/amhdmitx/amhdmitx0/frac_rate_policy
  fi
  if [ "${display_mode}" != "${display_mode_user}" ]; then
    echo "${display_mode_user}" > /sys/class/display/mode
    display_mode="${display_mode_user}"
  fi
fi

# Set framebuffer geometry to match the resolution
case ${display_mode} in
  *x*)   RES=${display_mode%%[ip]*} X=${RES%%x*} Y=${RES##*x};;
  480*)            X=720  Y=480  ;;
  576*)            X=720  Y=576  ;;
  720p*)           X=1280 Y=720  ;;
  2160p*)          X=3840 Y=2160 ;;
  *)               X=1920 Y=1080 ;;
esac

Y_VIRT=$((${Y} * 2))

fbset -fb /dev/fb0 -g ${X} ${Y} ${X} ${Y_VIRT} 32

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank
