#!/bin/sh

# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)

display_mode=$(cat /sys/class/display/mode)

for arg in $(cat /proc/cmdline); do
  case ${arg} in
    bootfrom*)
      bootfromext=1
      ;;
    BOOT_IMAGE=*)
      BOOT_IMAGE=${arg#*=}
      ;;
    boot=*)
      boot=${arg#*=}
      ;;
    disk=*)
      disk=${arg#*=}
      ;;
    hdmimode=*)
      hdmimode=${arg#*=}
      ;;
    frac_rate_policy=*)
      frac_rate_policy=${arg#*=}
      ;;
    native_4k_gui=*)
      native_4k_gui=${arg#*=}
      ;;
  esac
done

# Add information where to run CoreELEC from
if [ -z "$BOOT_IMAGE" -o -z "$boot" -o -z "$disk" ]; then
  cmdline=$(cat /proc/cmdline)
  if [ -n "$bootfromext" ]; then
    cmdline="$cmdline BOOT_IMAGE=kernel.img boot=LABEL=@BOOT_LABEL@ disk=LABEL=@DISK_LABEL@"
  fi
  echo "$cmdline" > /proc/cmdline
fi

# Enable HDMI output if cable is connected and not already enabled by u-boot
if [ "$(cat /sys/class/amhdmitx/amhdmitx0/hpd_state)" != "0" ]; then
  echo "null" > /sys/class/display/mode
  echo "$frac_rate_policy" > /sys/devices/virtual/amhdmitx/amhdmitx0/frac_rate_policy
  echo "$hdmimode" > /sys/class/display/mode
  display_mode="$hdmimode"
fi

# Set framebuffer geometry to match the resolution
case $display_mode in
  *x*)   RES=${display_mode%%[ip]*} X=${RES%%x*} Y=${RES##*x};;
  480*)            X=720  Y=480  ;;
  576*)            X=720  Y=576  ;;
  720p*)           X=1280 Y=720  ;;
  2160p*)          X=3840 Y=2160 ;;
  *)               X=1920 Y=1080 ;;
esac

if [ "$native_4k_gui" != "1" -a $X -gt 1920 ]; then
  X=1920
  Y=1080
fi

Y_VIRT=$(($Y * 2))

fbset -fb /dev/fb0 -g $X $Y $X $Y_VIRT 32
fbset -fb /dev/fb1 -g 32 32 32 32 32
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale
echo 1 > /sys/class/video/disable_video

# Enable scaling for 4K output
if [ "$native_4k_gui" != "1" ]; then
  case $display_mode in
    4k*|smpte*|2160*)
      echo 0 0 1919 1079 > /sys/class/graphics/fb0/free_scale_axis
      echo 0 0 3839 2159 > /sys/class/graphics/fb0/window_axis
      echo 0x10001 > /sys/class/graphics/fb0/free_scale
    ;;
  esac
fi

# Enable framebuffer device
echo 0 > /sys/class/graphics/fb0/blank

# Blank fb1 to prevent static noise
echo 1 > /sys/class/graphics/fb1/blank

# DEC_CONTROL_FLAG_DISABLE_FAST_POC
echo 4 > /sys/module/amvdec_h264/parameters/dec_control
