#!/bin/bash

# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2024-present Team LibreELEC (https://libreelec.tv)

# Regenerate 0001-user-addon-storage-location.patch
# Run tools/moby/gen-patches.sh

set -e

. config/options "moby"

TEMP_DIR=$(mktemp -d)
trap 'rm -rf "${TEMP_DIR}"' EXIT INT TERM

git -C ${TEMP_DIR} init --quiet
git -C ${TEMP_DIR} config user.email "patches@libreelec.tv"
git -C ${TEMP_DIR} config user.name "LibreELEC"

tar --strip-components=1 -xf ${SOURCES}/${PKG_NAME}/${PKG_SOURCE_NAME} -C ${TEMP_DIR}

git -C ${TEMP_DIR} add -A
git -C ${TEMP_DIR} commit --quiet -m "base"

find ${TEMP_DIR} -name "*.go" -print | xargs sed -i \
  's#/etc/docker#/storage/.kodi/userdata/addon_data/service.system.docker/config#g'

git -C ${TEMP_DIR} add -A
git -C ${TEMP_DIR} commit --quiet -m "${PKG_NAME} ${PKG_VERSION}: redirect addon storage paths

Redirect hardcoded upstream paths to LibreELEC addon storage locations
so ${PKG_NAME} ${PKG_VERSION} works correctly within the LibreELEC addon filesystem.

Source: ${PKG_SOURCE_NAME}
Generated by: tools/moby/gen-patches.sh
Generated on: $(date --utc '+%Y-%m-%d %H:%M:%S UTC')
Generator: $(git --version)

Path substitutions applied to all *.go files:
  /etc/docker -> /storage/.kodi/userdata/addon_data/service.system.docker/config

To regenerate this patch after a version bump, update PKG_VERSION in
package.mk and re-run:
  tools/moby/gen-patches.sh

Note: the script skips writing the patch file if the generated content
is identical to the existing patch (ignoring commit hash and timestamps),
avoiding unnecessary commits when the source version has not changed."

PATCH_OUT="${PKG_DIR}/patches/0001-user-addon-storage-location.patch"
NEW_PATCH="${TEMP_DIR}/new.patch"

git -C ${TEMP_DIR} format-patch HEAD~1 --stdout > "${NEW_PATCH}"

# Strip volatile headers (commit hash, date, timestamps) before comparing
strip_volatile() {
  grep -vE '^(From [0-9a-f]{40} |Date: |Generated on: |Generator: |[0-9]+\.[0-9]+\.[0-9]+$)'
}

if [ -f "${PATCH_OUT}" ] && \
   diff <(strip_volatile < "${NEW_PATCH}") <(strip_volatile < "${PATCH_OUT}") >/dev/null 2>&1; then
  echo "${PATCH_OUT##*/}: content unchanged, skipping update"
else
  cp "${NEW_PATCH}" "${PATCH_OUT}"
  echo "${PATCH_OUT##*/}: updated"
fi
